### PR TITLE
hide tildes in dark mode

### PR DESCRIPTION
**Pull request by taigacute**

### CODE REVIEW

**Comment by pickfire** [comment]
What about tildes in light mode? Is it better to hide it for feature parity? Or is it better to leave it be? (I personally like the tilde to know where the document ends)

**Comment by taigacute** [comment]
> 那么在光线模式下倾斜？隐藏它以进行功能奇偶校验更好吗？还是留下它更好？（我个人喜欢波形符号，知道文件的结尾）

Maybe  can add a variable to control it. i think don't need tildes to display the end of the file. we alose know the end when we move to the last line by `G` or some option. hide tide only in darkmode，casue i only use dark。

**Comment by pickfire** [comment]
Fair enough, controllable by a variable will be great but it should affect both light and dark mode for consistency.

翻译：对，可调变数更好，但亮暗模式该一致。（抱歉，技术术语欠佳）

**Comment by NLKNguyen** [comment]
Thanks! We can later add the same for light variant easily if people prefer.

**Pull request merged**
