### PR TITLE
Add support for vim-gitgutter

### PR DESCRIPTION
**Pull request by Kingorgg**
Adds support for the vim-gitgutter plugin.

Solves issue #172 ?

**Screenshots:**
Light Theme
image

Dark Theme
image

Light Theme (_:GitGutterLineHighlightsEnable_)
image

Dark Theme: (_:GitGutterLineHighlightsEnable_)
image

### CODE REVIEW

**Comment by hellovimo** [comment]
Hello ! I tried the above changes.. 

1. After setting the gitgutterlinehighlightsenable, when I open any git file which is been edited, the vim first prints some weird numbers as shown below and then opens up the file. Any guess what could be the issue ?

`H\ue0b0 31H    31H \ue0b231H Bufs 31H1;0M  1 31H
~                                                                                                                                   3;0M~                                                                                                                                   4;0M~                                                                                                                                   5;0M~                                                                                                                                   6;0M~                                                                                                                                   7;0M~                                                                                                                                   8;0M~                                                                                                                                   9;0M~                                                                                                                                   10;0M~                                                                                                                                   11;0M~                                                                                                                                   12;0M~                                                                                                                                   13;0M~                                                                                                                                   14;0M~                                                                                                                                   15;0M~                                                                                                                                   16;0M~                                                                                                                                   17;0M~                                                                                                                                   18;0M~                                                                                                                                   19;0M~                                                                                                                                   20;0M~                                                                                                                                   21;0M~                                                                                                                                   22;0M~                                                                                                                                   23;0M~                                                                                                                                   24;0M~                                                                                                                                   31H25;0M 
`

**Comment by NLKNguyen** [comment]
@hellovimo does that only happen with that gitgutter setting? and how about when you open in terminal Vim?

**Comment by hellovimo** [comment]
Hello @NLKNguyen 
1. This is happening when I open it in gvim and also in terminal VIM.
2. It just happens when I enable the :GitGutterLineHighlightsEnable and then open a modified git file. Then it throws up this weird numbers and then opens the file. Once the file it opened it shows that line highlight is happening as needed. 
3. But its just weird that such random numbers gets throws and it's disturbing.

**Comment by NLKNguyen** [comment]
That's strange. Does that happen only with PaperColor theme?

**Pull request merged**
