### PR TITLE
Add my site to README.md

### PR DESCRIPTION
**Pull request by pickfire**
2016-02-15-180401_1600x900_scrot

Thanks a lot for the colorscheme @NLKNguyen, I really appreciate it.

### CODE REVIEW

**Comment by NLKNguyen** [comment]
But how is it related to the color scheme?

**Comment by pickfire** [comment]
@NLKNguyen I use the most of the paper color platelets in the site. A creative idea, people can even use it outside their editor, like implementing it in their sites.

**Comment by NLKNguyen** [comment]
I close this because it needs to be something users can use in their work in order to be relevant to this particular project.

**Comment by pickfire** [comment]
No problem! :)

**Pull request closed without merging**
