### PR TITLE
Ninrod's dotfiles vim+tmux+zsh config is using papercolor light.

### PR DESCRIPTION
**Pull request by ninrod**
@NLKNguyen, I liked your theme so much that I've had it integrated into my full vim+tmux+zsh configuration. Thank you. Check it out [here][1].

screenshot-vi-tmux

[1]: <http://github.com/ninrod/dotfiles>

### CODE REVIEW

**Comment by NLKNguyen** [comment]
Great work, my friend :+1: . Glad you enjoy the theme :smile:  Keep it up!!

**Comment by pickfire** [comment]
@ninrod, looks nice. What terminal are you using?

And do you use the tmux with the true colors patch (the git head)?

**Comment by ninrod** [comment]
@NLKNguyen thank you. @pickfire, I use iTerm2 on mac and putty on windows on top of a centOS vagrant box. I don't use tmux with true colors. Just the normal tmux. I brew installed tmux and rolled with the standard version that comes with brew. That would be 1.8 on the time of the install I think.

**Comment by pickfire** [comment]
@ninrod I think the normal tmux doesn't support true colors yet, just the recent tmux. Your dotfiles's plugins seems a bit outdated, is that the ones that you are using?

**Comment by ninrod** [comment]
@pickfire What specific plugins do you think are outdated? My dotfile config doesn't require tmux truecolors. A simple 256colors capable terminal will do.

**Comment by pickfire** [comment]
@ninrod The vim plugins section.

**Comment by ninrod** [comment]
I'm using those on the vim plugins section. Why do you think they're outdated? They seem pretty up to date to me.

**Comment by pickfire** [comment]
@ninrod There isn't papercolor.vim that you are using.

**Comment by NLKNguyen** [comment]
@pickfire You can create a dedicate issue on his repository if that concerns you, you know :)

**Comment by pickfire** [comment]
@NLKNguyen Ops, sorry for flooding this pull request.

**Pull request merged**
